# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: portable.jre
PackageVersion: "1.0"
PackageLocale: en-US
Publisher: Megan
PackageName: jre
License: GNU
ShortDescription: Portable JRE
ManifestType: defaultLocale
ManifestVersion: 1.6.0
